### ISSUE TITLE
Joining the list of Awesome lists

### ISSUE THREAD

**Issue by OriginalFannibal** [Kazhnuz/awesome-gnome#20]
@Kazhnuz We've been around for longer than a month and have a decent and definitely well curated collection of apps. I think it is time to add ourselves to [awesome](https://github.com/sindresorhus/awesome).

Let's go through the contribution guidelines again and add anything that we need to do to get our list ready and worthy to go up there to this issue and work through them until we are ready and then you can open a PR there.

Here are the contribution guidelines for easy reference:  

- Search previous suggestions before making a new one, as yours may be a duplicate.
- Make sure the list is useful before submitting. That implies it has enough content and every item has a good succinct description.
- Make an individual pull request for each suggestion.
- Use title-casing (AP style).
- Use the following format: [List Name](link)
- Link additions should be added to the bottom of the relevant category.
- New categories or improvements to the existing categorization are welcome.
- Check your spelling and grammar.
- Make sure your text editor is set to remove trailing whitespace.
- The pull request and commit should have a useful title.  
- The body of your commit message should contain a link to the repository.

**Comment by OriginalFannibal** [comment]
*The following is the PR template from the awesome lists repository*

**[Insert URL to the list here]**

**[Explain what this list is about and why it should be included here]**


# By submitting this pull request I confirm I've read and complied with the below requirements.

**Please read it multiple times. I spent a lot of time on these guidelines and most people miss a lot.**

- I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [instructions for creating a list](https://github.com/sindresorhus/awesome/blob/master/create-list.md).
- This pull request has a descriptive title.<br>For example, `Add Name of List`, not `Update readme.md` or `Add awesome list`.
- The entry in the Awesome list should:
	- Include a short description about the project/theme of the list. **It should not describe the list itself.**<br>Example: `- [Fish](…) - User-friendly shell.`, not `- [Fish](…) - Resources for Fish.`.
	- Be added at the bottom of the appropriate category.
- The list I'm submitting complies with these requirements:
	- **Has been around for at least 30 days.**<br>That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	- It's the result of hard work and the best I could possibly produce.
	- Non-generated Markdown file in a GitHub repo.
	- **Includes a succinct description of the project/theme at the top of the readme.** [(Example)](https://github.com/willempienaar/awesome-quantified-self)
	- The repo should have `awesome-list` & `awesome` as [GitHub topics](https://help.github.com/articles/about-topics). I encourage you to add more relevant topics.
	- Not a duplicate.
	- Only has awesome items. Awesome lists are curations of the best, not everything.
	- Includes a project logo/illustration whenever possible.
		- Placed at the top-right of the readme. [(Example)](https://github.com/sindresorhus/awesome-electron)
		- The image should link to the project website or any relevant website.
		- The image should be high-DPI. Set it to maximum half the width of the original image.
	- Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	- Includes the [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge).
		- Should be placed on the right side of the readme heading.
		- Should link back to this list.
	- Has a Table of Contents section.
		- Should be named `Contents`, not `Table of Contents`.
		- Should be the first section in the list.
		- Should only have one level of sub-lists, preferably none.
	- Has an [appropriate license](https://github.com/sindresorhus/awesome/blob/master/awesome.md#choose-an-appropriate-license).
		- That means something like CC0, **not a code licence like MIT, BSD, Apache, etc.**
		- If you use a license badge, it should be SVG, not PNG.
	- Has [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#include-contribution-guidelines).
		- The file should be named `contributing.md`. Casing is up to you.
	- Has consistent formatting and proper spelling/grammar.
		- Each link description starts with an uppercase character and ends with a period.<br>Example: `- [AVA](…) - JavaScript test runner.`
		- Drop all the `A` / `An` prefixes in the descriptions.
		- Consistent and correct naming. For example, `Node.js`, not `NodeJS` or `node.js`.
	- Doesn't include a Travis badge.<br>You can still use Travis for list linting, but the badge has no value in the readme.
- Go to the top and read it again.


I am planning on working on dropping the `A`/`An' prefixes in the descriptions as recommended here.

**Comment by Kazhnuz** [comment]
Yep, good idea ! Let's see what's done and still todo on the list of guidelines. 

- [x] Has been around for at least 30 days.
- [x] It's the result of hard work and the best I could possibly produce. (I'll try and see what applications, extensions and themes we could have missed)
- [x] Non-generated Markdown file in a GitHub repo.
- [x] Includes a succinct description of the project/theme at the top of the readme.
- [x] The repo should have awesome-list & awesome as GitHub topics. I encourage you to add more relevant topics.
- [x] Not a duplicate.
- [x] Only has awesome items. Awesome lists are curations of the best, not everything. (Issue(s) : #17 )
- [ ] Includes a project logo/illustration whenever possible.
  - [ ] Placed at the top-right of the readme. (Example)
  - [ ] The image should link to the project website or any relevant website.
  - [ ] The image should be high-DPI. Set it to maximum half the width of the original image.
- [x] Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
- [x] Includes the Awesome badge.
  - [x] Should be placed on the right side of the readme heading.
  - [x] Should link back to this list.
- [x] Has a Table of Contents section.
  - [x] Should be named Contents, not Table of Contents.
  - [x] Should be the first section in the list.
  - [x] Should only have one level of sub-lists, preferably none. (we only have one. Having none would be difficult, especially with how many extension there is)
- [x] Has an appropriate license.
  - [x] That means something like CC0, not a code licence like MIT, BSD, Apache, etc.
  - [ ] If you use a license badge, it should be SVG, not PNG. (we don't have one, so moot point)
- [x] Has contribution guidelines. (PR : #7)
  - [x] The file should be named contributing.md. Casing is up to you.
- [x] Has consistent formatting and proper spelling/grammar. (you made several PR improving it a lot, thanks !)
  - [x] Each link description starts with an uppercase character and ends with a period. (PR : #22)
  - [x] Example: - [AVA](…) - JavaScript test runner.
  - [x] Drop all the A / An prefixes in the descriptions. 
  - [x] Consistent and correct naming. For example, Node.js, not NodeJS or node.js.
- [x] Doesn't include a Travis badge.
  - [ ] You can still use Travis for list linting, but the badge has no value in the readme. (we don't use it, so moot point)

**Comment by OriginalFannibal** [comment]
Are we good to go now? I don't think we have anything more to do. All the best with the PR over there :)

**Comment by Kazhnuz** [comment]
Yes, I think we're good now ! Do you want me to do the PR (and for the category, I think GNOME should be on "Platforms", under Linux) ?

**Comment by OriginalFannibal** [comment]
You're the right one to make the PR :)  
I too think platforms is the suitable category for this list but do remember to put it at the end of that category as that is what is recommended.

**Comment by Kazhnuz** [comment]
PR done :) Now, let's wait and see what the maintainer of awesome have to say, if there are things to be done.

**Comment by Kazhnuz** [comment]
Yay \o/ Closing this issue.
